### ISSUE TITLE
Doesn't seem to be working.

### ISSUE THREAD

**Issue by Shadester** [marcosgriselli/Sizes#25]
## Expected Behavior

I added the pod in the podfile and compiled without adding Sizes to the appdelegate.

## Actual Behavior

Showing Recent Messages
:-1: invalid task ('StripNIB /Users/shades/Library/Developer/Xcode/DerivedData/demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphoneos/Sizes/ConfigurationViewController.nib') with mutable output but no other virtual output node (in target 'Sizes')

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 0.3.0, Xcode 10.0
  - Platform:
  - Subsystem:

**Comment by marcosgriselli** [comment]
Hi @Shadester, this seems like a derived data issue rather than a problem with Sizes. I recommend you delete your Xcode derived data and try again, you can check how to do that [here](https://stackoverflow.com/a/39495772/2892512).

**Comment by Shadester** [comment]
Negative, that didn't work. I was running on device first, but I switched to emulator and same error.

**Comment by Shadester** [comment]
Showing Recent Messages

Prepare build
note: Using new build systemnote: Planning buildnote: Constructing build description

Build system information
error: invalid task ('StripNIB /Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController.nib') with mutable output but no other virtual output node (in target 'Sizes')
Build system information
error: invalid task ('StripNIB /Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController~ipad.nib') with mutable output but no other virtual output node (in target 'Sizes')
Build system information
error: invalid task ('StripNIB /Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController~iphone.nib') with mutable output but no other virtual output node (in target 'Sizes')
Build system information
warning: no rule to process file '/Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController.nib' of type 'wrapper.nib'for architecture 'i386' (in target 'Sizes')
Build system information
warning: no rule to process file '/Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController~iphone.nib' of type 'wrapper.nib'for architecture 'i386' (in target 'Sizes')
Build system information
warning: no rule to process file '/Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController~ipad.nib' of type 'wrapper.nib'for architecture 'i386' (in target 'Sizes')
Build system information
warning: no rule to process file '/Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController.nib' of type 'wrapper.nib'for architecture 'x86_64' (in target 'Sizes')
Build system information
warning: no rule to process file '/Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController~iphone.nib' of type 'wrapper.nib'for architecture 'x86_64' (in target 'Sizes')
Build system information
warning: no rule to process file '/Users/shades/Library/Developer/Xcode/DerivedData/Demo-bualkkfeqqxibmctwpedvrosiyuh/Build/Products/Preview-Debug-iphonesimulator/Sizes/ConfigurationViewController~ipad.nib' of type 'wrapper.nib'for architecture 'x86_64' (in target 'Sizes')


Build failed    10/22/18, 15:00    3.2 seconds

**Comment by marcosgriselli** [comment]
Device or simulator shouldn't make any difference. I'd close Xcode, delete derived data, update Sizes, open Xcode, clean project (cmd + shift + K) and try to build again. I just created a project from scratch and did the same as you with no errors.

**Comment by Shadester** [comment]
I thought upgrading to 0.4.2 would work. No luck. I tried the things you recommended, but it doesn't work. Thanks for the help, though.
