### ISSUE TITLE
Sizes Configuration Panel hides for good, meaning the project has to be rerun to test fully on all device sizes

### ISSUE THREAD

**Issue by wolfej1994** [marcosgriselli/Sizes#27]
Once dismissed there should be a way to get the configuration panel back onto the screen, potentially using the same swiping gesture that was used to dismiss it.

What actually happens is that there is no way to get the panel back onto the screen, which means I have to run the that app multiple times to test thoroughly on different devices. 

If there is a way to solve this I cannot find anything in the documentation of the existing/closed issues.

  1. Setup sizes in your project the way that the documentation states (using a SizesWindow)
  2. Hide the configuration panel by swiping down on it
  3. Attempt to swipe it back up or show it again in any way you can imagine.

  - Version: 0.4.3
  - Platform: iOS Simulator
  - iOS: 12.1

**Comment by b-onc** [comment]
You should be able to display the configuration by shaking the device (or whatever option you've used to get the configuration window) (simulator shaking gesture: Shift+Cmd+Z) whenever you want.

**Comment by marcosgriselli** [comment]
As @b-onc said. Shaking is the only way to show the configuration panel with an action. Otherwise, you'll have to set the `shakeGestureEnabled` from `SizesWindow` to `false` and trigger the presentation manually with:
```swift 
if let sizesWindow = UIApplication.shared.windows.first(where: { $0 is SizesWindow }) {
    sizesWindow.presentConfiguration()
}
```
